// tslint:disable
/**
 * Name Done - Auth Service
 * An authentication service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EmailConfirmationRequiredResponseDto
 */
export interface EmailConfirmationRequiredResponseDto {
    /**
     * An informational message indicating the need for email confirmation
     * @type {string}
     * @memberof EmailConfirmationRequiredResponseDto
     */
    message: string;
}
